apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-client-deployment
  labels:
    app: socket-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-client
  template:
    metadata:
      labels:
        app: socket-client
    spec:
      containers:
      - name: socket-client-container
        image: samchan0221/dummy-node-socket
        command: ["npm", "run", "client:start"]
        ports:
        - containerPort: 3001
        env:
        - name: podId
          valueFrom:
            resourceFieldRef:
              containerName: socket-client-container
              resource: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: socket-client-svc
  labels:
    app: socket-client-svc
spec:
  ports:
  - port: 80
    containerPort: 3001
  selector:
    app: socket-client
