apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server-deployment
  labels:
    app: socket-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server-container
        image: samchan0221/dummy-node-socket:v0.0.1
        command: ["npm", "run", "server:start"]
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server-svc
  labels:
    app: socket-server-svc
spec:
  ports:
  - port: 80
    targetPortcontainerPort: 3000
  selector:
    app: socket-server
